name: ci

on:
  push:
    paths-ignore:
      - "doc/**"
      - "**.rst"

jobs:
  ci:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/shiguredo/erlang:otp-29.0.1-aws-lc-v1.73.0-ubuntu-26.04-x86_64
    steps:
      - uses: actions/checkout@v6
      - run: make ci

  slack_notify:
    needs:
      - ci
    runs-on: ubuntu-slim
    if: always()
    timeout-minutes: 5
    permissions:
      actions: read
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: ${{ secrets.SLACK_INTERNAL_CHANNEL }}
          notify_mode: failure_and_fixed
        env:
          GH_TOKEN: ${{ github.token }}
