name: ci

on:
  push:
    paths-ignore:
      - "doc/**"
      - "**.rst"
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: shiguredo/shiguredo-erlang:otp-26.0.2-openssl-3.1.1-ubuntu-22.04-x86_64
    steps:
      - uses: actions/checkout@v3
      - run: make ci
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_INTERNAL_CHANNEL }}
          SLACK_COLOR: danger
          SLACK_TITLE: Failure test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
