name: ci

on:
  push:
    paths-ignore:
      - "doc/**"
      - "**.rst"

jobs:
  efmt_job:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    env:
      # gh release download で使用する
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      EFMT_VERSION: "0.21.0"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # "Install efmt" の中でパスを追加しても反映されなかったのでステップを分ける
      - name: Add path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install efmt
        run: |
          gh release download "${EFMT_VERSION}" \
            -R sile/efmt \
            -p "efmt-${EFMT_VERSION}.x86_64-unknown-linux-musl" \
            -D .
          chmod 755 "efmt-${EFMT_VERSION}.x86_64-unknown-linux-musl"
          mkdir -p "$HOME/.local/bin"
          mv "efmt-${EFMT_VERSION}.x86_64-unknown-linux-musl" "$HOME/.local/bin/efmt"

      - name: Verify efmt
        run: efmt --version

      - run: make efmt-check

  ci:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/shiguredo/erlang:otp-29.0.6-aws-lc-v5.8.0-ubuntu-26.04-x86_64
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: make ci

  slack_notify:
    needs:
      - efmt_job
      - ci
    runs-on: ubuntu-slim
    if: always()
    timeout-minutes: 5
    permissions:
      actions: read
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: ${{ secrets.SLACK_INTERNAL_CHANNEL }}
          notify_mode: failure_and_fixed
        env:
          GH_TOKEN: ${{ github.token }}
